---
- name: Add MongoDB repository key
  become: yes
  apt_key:
    url: http://www.mongodb.org/static/pgp/server-3.4.asc
    state: present
    validate_certs: no  # TODO: change this to yes after it's fixed

- name: Add official MongoDB repository
  become: yes
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.3 multiverse
    state: present

- name: Install MongoDB
  become: yes
  apt: name={{ item }} state=latest update_cache=true
  with_items:
    - mongodb-org-unstable
    - python3-pymongo

- name: Create mongo.service file
  become: yes
  template:
    src: mongod.service_template.j2
    dest: /lib/systemd/system/mongod.service
    force: yes

- name: Create DB and user setup script
  become: yes
  template:
    src: setup_db.js.j2
    dest: /tmp/setup_db.js
    force: yes

- name: Reconfigure mongod
  become: yes
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    force: yes

- name: Restart MongoDB
  become: yes
  service:
    name: mongod
    state: restarted

- pause: seconds=30

- name: Setup DB
  become: yes
  shell: mongo admin < /tmp/setup_db.js

- name: Restart MongoDB
  become: yes
  service:
    name: mongod
    state: restarted
